Convert soql response to dataframe (READY FOR REVIEW)
wiris/santoku pull request #14
Opened 2021-04-20 10:20 UTC by roger-wiris

- Add function to convert soql response to Pandas DataFrame 
- Add test for soql_response_to_dataframe function

2021-04-20 18:50 UTC, dmas-at-wiris requested changes
@HENRYQIULO why was everything reformated? Did we change anything from black?

2021-04-20 18:50 UTC, dmas-at-wiris commented on santoku/salesforce/lightning.py
> +        Flattens a SOQL response and converts it into a pandas DataFrame.
Flattens **an** SOQL...

2021-04-20 18:50 UTC, dmas-at-wiris commented on santoku/salesforce/lightning.py
> +        Parameters
Review previous function docstring. We are missing some description in the parameters.

2021-04-20 18:50 UTC, dmas-at-wiris commented on santoku/salesforce/lightning.py
> +        To flatten the response json we use the function json_normalize from Pandas [1]
The response **JSON** object is flattened using the Pandas json_normalize function [1]

2021-04-20 18:50 UTC, dmas-at-wiris commented on santoku/salesforce/lightning.py
> +        import pandas as pd
remove this, not necessary any more

2021-04-20 18:50 UTC, dmas-at-wiris commented on santoku/salesforce/lightning.py
> +    def soql_response_to_dataframe(
Shall this method be static?

2021-04-21 09:13 UTC, roger-wiris commented
> @HENRYQIULO why was everything reformated? Did we change anything from black?
@dmas-at-wiris The last version of black re-implemented support for explicit trailing commas. See reference [here](https://github.com/psf/black/blob/master/CHANGES.md#black-1). With the previous version (19.10b0), having the trailing comma, black didn't split the line. However, with the newer version (20.8b0), it does so. Hence, we will remove the trailing commas to avoid the split.

2021-04-23 08:44 UTC, HENRYQIULO approved these changes

2021-04-23 08:45 UTC, merged