Add URL Handler (READY FOR REVIEW)
wiris/santoku pull request #16
Opened 2021-05-04 16:43 UTC by HENRYQIULO

2021-05-04 16:54 UTC, dmas-at-wiris commented on santoku/salesforce/lightning.py
>          retrieve data from a single salesforce object or from multiple objects that are related.
Salesforce

2021-05-04 16:55 UTC, dmas-at-wiris commented on santoku/salesforce/lightning.py
>              Comlumns that do not contain any value will be removed. Set to false by default.
Columns...

2021-05-04 16:57 UTC, dmas-at-wiris commented on santoku/utils/url_handler.py
> +        num_subdomains : int
, Optional

2021-05-04 16:57 UTC, dmas-at-wiris commented on santoku/utils/url_handler.py
> +        return_invalid_urls : bool
, Optional

2021-05-04 16:58 UTC, dmas-at-wiris commented on santoku/utils/url_handler.py
> +            return ""
Shall we raise an exception?

2021-05-04 16:59 UTC, dmas-at-wiris commented on santoku/utils/url_handler.py
> +        return_invalid_urls : bool
, Optional

2021-05-04 17:00 UTC, dmas-at-wiris commented on santoku/utils/url_handler.py
> +        domain = tldextract.extract(url=url).domain
any exception to handle?

2021-05-04 17:02 UTC, dmas-at-wiris requested changes
See comments

2021-05-05 08:33 UTC, dmas-at-wiris commented on santoku/utils/test/test_url_handler.py
> +        ("https://example.co.uk", 0, "example.co.uk", "example.co.uk"),
maybe add a test with port?

2021-05-05 10:14 UTC, roger-wiris approved these changes

2021-05-05 10:16 UTC, dmas-at-wiris commented on santoku/utils/url_handler.py
> +            raise InvalidURLError(f"The given URL '{url}' does not contain domain or suffix.")
The {url} URL does not contain domain or suffix

2021-05-05 10:16 UTC, dmas-at-wiris commented on santoku/utils/url_handler.py
> +            raise InvalidURLError(f"The given URL '{url}' does not contain domain or suffix.")
Same as before

2021-05-05 10:17 UTC, dmas-at-wiris approved these changes
Change those two comments and merge directly. Good job! :)

2021-05-05 10:24 UTC, merged